// Project Management Dashboard Configuration

export const PROJECT_CONFIG = {
  name: 'Brand Builder Pro Development',
  totalDuration: '10-12 months',
  phases: [
    { phase: 1, name: 'Brand Strategy & Positioning', duration: '6-8 weeks' },
    { phase: 2, name: 'Brand Expression & Identity', duration: '8-10 weeks' },
    { phase: 3, name: 'Brand Experience Design', duration: '12-14 weeks' },
    { phase: 4, name: 'Brand Activation & Launch', duration: '8-10 weeks' },
    { phase: 5, name: 'Implementation Support', duration: '6-12 months' },
  ],
};

export const DELIVERABLES_CONFIG: Record<string, string[]> = {
  phase1: [
    'Brand Audit Report',
    'Competitive Landscape Analysis',
    'Customer Perception Study',
    'Category Trends Report',
    'Stakeholder Interview Synthesis',
    'Brand Strategy Document',
    'Brand Purpose, Vision, Mission',
    'Brand Positioning Statement',
    'Brand Personality Framework',
    'Target Audience Personas',
    'Brand Architecture',
    'Pricing Strategy Recommendations',
  ],
  phase2: [
    'Brand Story',
    'Tagline and Messages',
    'Brand Voice Guidelines',
    'Messaging Framework',
    'Logo System',
    'Color Palette',
    'Typography System',
    'Photography Style Guide',
    'Social Media Templates',
    'Website Design Direction',
    'Packaging Design System',
    'Gift Packaging Solutions',
    'Channel Architecture Strategy',
    'Size Architecture',
    'Price Architecture Framework',
  ],
  phase3: [
    'Customer Journey Maps',
    'CX Improvement Roadmap',
    'Store Design Concept',
    'Visual Merchandising Guidelines',
    'Website UX/UI Recommendations',
    'Social Media Strategy',
    'Content Calendar Template',
    'Influencer Marketing Playbook',
    'UGC Strategy & Campaigns',
    'Content Production Guidelines',
    'PDP Templates',
    'SEO & Marketplace Optimization',
    'Review Strategy',
    'Provenance Story Bible',
    'Origin Story Development',
  ],
  phase4: [
    'Brand Launch Plan',
    'Launch Campaign Concept',
    'Performance Marketing Strategy',
    'Community Building Strategy',
    'CRM & Lifecycle Framework',
    'Customer Segmentation Strategy',
    'Loyalty Program Architecture',
    'Festive Calendar & Strategy',
    'Corporate Gifting Catalogue',
    'B2B Sales Toolkit',
    'Retail Brand Standards',
    'POSM Kit',
    'Performance Creative System',
    'Brand Guidelines Manual',
    'Brand Governance Policy',
  ],
  phase5: [
    'Monthly Consultation Calls',
    'Quarterly Brand Health Reviews',
    'Innovation Framework',
    'NPD Launch Playbook',
    'Trend Analysis Reports',
    'Brand Evolution Strategy',
    'Crisis Management Protocols',
  ],
};
